apiVersion: v1
kind: ConfigMap
metadata:
  name: hello
data:
  foo: bar
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hook
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  project: default
  source:
    repoURL: file:///tmp/app-hook
    targetRevision: HEAD
    path: '.'
    directory:
      include: 'job.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true