apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-with-hook
  labels:
    foo: bar
spec:
  project: default
  source:
    repoURL: https://github.com/alexmt/app-hook
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hook
  # this is probably messes things up
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alexmt/app-hook
    targetRevision: HEAD
    path: '.'
    directory:
      include: 'job.yaml'
  destination:
    name: laptop
    namespace: argocd
  syncPolicy:
    automated:
      prune: true