apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'sleep 10; echo "Hello, World!"']
      restartPolicy: Never
  backoffLimit: 4